import { trackSelfDescribingEvent, type CommonEventProperties, type SelfDescribingJson } from '@snowplow/browser-tracker';
// Automatically generated by Snowtype

/**
 * Structure for events that identify a user, with their user pieces
 */
export type CustomerIdentification = {
    /**
     * Customer's email address
     */
    email?: null | string;
    /**
     * The customer's phone
     */
    phone?: null | string;
}

/**
 * Creates a Snowplow Event Specification entity.
 */
export function createEventSpecification(eventSpecification: Omit<EventSpecification, 'data_product_domain'> & Partial<Pick<EventSpecification, 'data_product_domain'>>){
    return {
        schema:
            'iglu:com.snowplowanalytics.snowplow/event_specification/jsonschema/1-0-4',
        data: eventSpecification,
    }
}

/**
 * Automatically attached context for event specifications
 */
interface EventSpecification {
    id: string;
    version: number;
    name: string;
    data_product_id: string;
    data_product_name: string;
    data_product_domain?: string;
}

type ContextsOrTimestamp<T = any> = Omit<CommonEventProperties<T>, 'context'> & { context?: SelfDescribingJson<T>[] | null | undefined }
/**
 * Track a Snowplow event for CustomerIdentification.
 * Structure for events that identify a user, with their user pieces
 */
export function trackCustomerIdentification<T extends {} = any>(customerIdentification: CustomerIdentification & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = customerIdentification;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leosenterprises/customer_identification/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow CustomerIdentification entity.
 */
export function createCustomerIdentification(customerIdentification: CustomerIdentification){
    return {
        schema: 'iglu:com.leosenterprises/customer_identification/jsonschema/1-0-0',
        data: customerIdentification
    }
}

/**
 * Tracks a CustomerIdentification event specification.
 * ID: c7c1b82b-2a65-4d9c-a370-26131e19835a
 */
export function trackCustomerIdentificationSpec(customerIdentification: CustomerIdentification & ContextsOrTimestamp, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: 'c7c1b82b-2a65-4d9c-a370-26131e19835a',
        version: 1,
        name: 'Customer Identification',
        data_product_id: 'd9f5e443-f18b-40a8-84dc-22ca8513dd3f',
        data_product_name: 'Leo&#x27;s Money Maker Tracking Plan',
        data_product_domain: 'Tracking'
    });

    const context = Array.isArray(customerIdentification.context)
        ? [...customerIdentification.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedCustomerIdentification = {
        ...customerIdentification,
        context,
    };

    trackCustomerIdentification<Record<string, unknown> | EventSpecification>(modifiedCustomerIdentification, trackers);
}


